#!/usr/bin/env python3
"""
Test Report Management Tool

This script helps manage test reports generated by the crypto data collector.
"""

import os
import json
import glob
from datetime import datetime, timedelta
from pathlib import Path
import argparse


def list_reports(reports_dir="reports"):
    """List all test reports in the reports directory."""
    if not os.path.exists(reports_dir):
        print(f"📂 Reports directory '{reports_dir}' does not exist")
        return
    
    print(f"📂 Test Reports in '{reports_dir}':")
    print("=" * 50)
    
    # Find all report files
    report_files = []
    for pattern in ["*.json", "*.txt", "*.html"]:
        report_files.extend(glob.glob(os.path.join(reports_dir, pattern)))
    
    if not report_files:
        print("No reports found")
        return
    
    # Sort by modification time
    report_files.sort(key=lambda x: os.path.getmtime(x), reverse=True)
    
    for file_path in report_files:
        file_size = os.path.getsize(file_path)
        file_time = datetime.fromtimestamp(os.path.getmtime(file_path))
        
        print(f"📄 {os.path.basename(file_path)}")
        print(f"   Size: {file_size:,} bytes")
        print(f"   Modified: {file_time.strftime('%Y-%m-%d %H:%M:%S')}")
        print()


def clean_old_reports(reports_dir="reports", days=30):
    """Clean reports older than specified days."""
    if not os.path.exists(reports_dir):
        print(f"📂 Reports directory '{reports_dir}' does not exist")
        return
    
    cutoff_date = datetime.now() - timedelta(days=days)
    
    print(f"🧹 Cleaning reports older than {days} days...")
    print(f"   Cutoff date: {cutoff_date.strftime('%Y-%m-%d %H:%M:%S')}")
    
    cleaned_count = 0
    for pattern in ["*.json", "*.txt", "*.html"]:
        for file_path in glob.glob(os.path.join(reports_dir, pattern)):
            file_time = datetime.fromtimestamp(os.path.getmtime(file_path))
            if file_time < cutoff_date:
                print(f"   Deleting: {os.path.basename(file_path)}")
                os.remove(file_path)
                cleaned_count += 1
    
    print(f"✅ Cleaned {cleaned_count} old reports")


def show_report_summary(reports_dir="reports"):
    """Show a summary of all reports."""
    if not os.path.exists(reports_dir):
        print(f"📂 Reports directory '{reports_dir}' does not exist")
        return
    
    print(f"📊 Test Reports Summary")
    print("=" * 50)
    
    # Count different types of reports
    live_reports = len(glob.glob(os.path.join(reports_dir, "test_report_live_*.json")))
    general_reports = len(glob.glob(os.path.join(reports_dir, "test_report_*.txt")))
    other_reports = len(glob.glob(os.path.join(reports_dir, "*.json"))) - live_reports
    
    print(f"📈 Live Test Reports: {live_reports}")
    print(f"📝 General Test Reports: {general_reports}")
    print(f"📄 Other Reports: {other_reports}")
    print(f"📁 Total Files: {live_reports + general_reports + other_reports}")
    
    # Show disk usage
    total_size = sum(os.path.getsize(f) for f in glob.glob(os.path.join(reports_dir, "*")))
    print(f"💾 Total Size: {total_size:,} bytes ({total_size/1024/1024:.2f} MB)")
    
    # Show latest report
    all_files = glob.glob(os.path.join(reports_dir, "*"))
    if all_files:
        latest_file = max(all_files, key=os.path.getmtime)
        latest_time = datetime.fromtimestamp(os.path.getmtime(latest_file))
        print(f"🕐 Latest Report: {os.path.basename(latest_file)}")
        print(f"   Generated: {latest_time.strftime('%Y-%m-%d %H:%M:%S')}")


def main():
    parser = argparse.ArgumentParser(description="Manage test reports")
    parser.add_argument("--reports-dir", default="reports", help="Reports directory path")
    
    subparsers = parser.add_subparsers(dest="command", help="Available commands")
    
    # List command
    list_parser = subparsers.add_parser("list", help="List all reports")
    
    # Clean command
    clean_parser = subparsers.add_parser("clean", help="Clean old reports")
    clean_parser.add_argument("--days", type=int, default=30, help="Delete reports older than this many days")
    
    # Summary command
    summary_parser = subparsers.add_parser("summary", help="Show report summary")
    
    args = parser.parse_args()
    
    if args.command == "list":
        list_reports(args.reports_dir)
    elif args.command == "clean":
        clean_old_reports(args.reports_dir, args.days)
    elif args.command == "summary":
        show_report_summary(args.reports_dir)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()